- platform: systemmonitor
  scan_interval: 60
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot

- platform: command_line
  scan_interval: 120
  name: IP addresse
  command: "curl ifconfig.me"
